### ISSUE TITLE
Breeze icon theme is broken on LXQt

### ISSUE THREAD

**Issue by YamashitaRen** [lxde/lxqt#1048]
Pictures are worth hundred words : 
Started Plasma5, opened PCManFM : https://someimage.com/EyiVCua
Started LXQt, opened PCManFM : https://someimage.com/c3BKq29

At first I thought that it was a Breeze bug : https://bugs.kde.org/show_bug.cgi?id=361192
But now that I have seen that Breeze works fine on Plasma5, I'd rather say that it's a LXQt bug...

Summary of the bug : lowres icon sizes are used for some icons if you use the Breeze theme in LXQt.

**Comment by Esclapion** [comment]
Lxqt and Kde are two differents desktops, Lxqt has not to have exactly the same parameters than Kde.

Else, for Lxqt, you can change it in the settings of pcmanfm-qt, Edit -> Preferences -> Display -> Size of the big icons ?

**Comment by stefonarch** [comment]
I'm using breeze on arch and everything is ok here except for the computer icon:
 
![schermata](https://cloud.githubusercontent.com/assets/10681413/15065942/05159ebe-1365-11e6-9917-0158a2950ec5.png)

**Comment by stefonarch** [comment]
PS: are you running the latest git version of pcmanfm-qt? 
Icon aspect in side panel dipends on settings in Preferences > Display > Size of side pane icons; 24px and less displays your picture, 32px and more displays my screenshot.

**Comment by luis-pereira** [comment]
@YamashitaRen I do confirm @stefonarch  findings. It works as expected to me.

**Comment by tsujan** [comment]
I think @YamashitaRen means that `mimetypes/file-types-small` from Breeze shouldn't be used in the folder view, whose icons are large enough. I'll check it on Manjaro soon.

**Comment by YamashitaRen** [comment]
No @stefonarch, you have the bug too !!!
In your screen, 2-finger, amv-ffmpeg, etc... use the ugly 24x icons, when they should use the 48x icons.
Exactly like @tsujan says.

I'm sorry for my misleading bug report. I wrongly assumed that side panels icons were affected too.

**Comment by stefonarch** [comment]
When I check in Dolphin (on LXQt, I dont have kde session) the icons are exactly the same, execpt for folders which are they grey ones, no idea why.

**Comment by gilir** [comment]
Same bug that #343 ?

**Comment by YamashitaRen** [comment]
Ah ! I knew that I saw this bug, I even commented on it... Sorry, I wasn't able to find it back...
@stefonarch Yep, bug happens in Doplhin on LXQt too.
No bug in Dolphin/PCManFM-Qt on KDE.

**Comment by luis-pereira** [comment]
The computer icon on the side pane is clearly wrong.
What else is ?
![screen-2016-05-06-13-05-43](https://cloud.githubusercontent.com/assets/62877/15072555/706a897e-138b-11e6-8c8a-b7825437c44e.png)

**Comment by YamashitaRen** [comment]
@luis-pereira 
xpto.txt, xpto.mpeg, qlgt.db
Try decreasing the size of big icons, directory icons will change but theses three files icons will stay the same. Theses are the 24x icons you can find in /usr/share/icons/breeze/*/24.

**Comment by luis-pereira** [comment]
@YamashitaRen  It works Ok on my system
![screen-2016-05-06-13-13-13](https://cloud.githubusercontent.com/assets/62877/15072687/5f8f4f80-138c-11e6-8b8f-cec3db7f6075.png)

**Comment by YamashitaRen** [comment]
@luis-pereira 
Go to 24. Size of theses three icons will change but not look. Size and look of other icons will change.
Here is the right look for 48/64 : https://someimage.com/EyiVCua

In LXQt, 24x icons are (sometimes) upscaled when bigger res icons should be used instead.

**Comment by luis-pereira** [comment]
@YamashitaRen 
![screen-2016-05-06-14-23-46](https://cloud.githubusercontent.com/assets/62877/15074318/31cc28de-1396-11e6-8ea4-b2033542a5d1.png)

**Comment by luis-pereira** [comment]
@YamashitaRen Now I understand it :smile:

**Comment by tsujan** [comment]
I confirm @YamashitaRen's observation. The situation with Breeze is a mess, with regard to both the chosen icons and their sizes.

However, that isn't a surprise to me. Although I don't know the exact cause yet, the icons are set by libfm, which is a hybrid partly based on Qt and partly based on GLib; hence the complication.

**Comment by Esclapion** [comment]
![x](https://cloud.githubusercontent.com/assets/3512979/15075123/0a70ff3c-13a3-11e6-93fb-f178e927fc80.png)

**Comment by tsujan** [comment]
@Esclapion 
All icon themes except for KDE ones are shown correctly, whether they are PNG based or SVG based.

@palinek Would you please examine this? I can do nothing in libfm-qt. My guess is that it's related to libqtxdg.

**Comment by tsujan** [comment]
An screenshot that shows SVG icon themes are shown correctly too:

![2016-05-06-18 33 59-scrot](https://cloud.githubusercontent.com/assets/981076/15075440/9e6d3b7c-13b9-11e6-9296-3dadaaa8d39b.png)

We can't say that Breeze isn't compatible with GLib because spacefm shows Breeze icons correctly.

**Comment by luis-pereira** [comment]
@tsujan PCManFM-Qt does not use libqtxdg

**Comment by tsujan** [comment]
@luis-pereira I know. The problem shouldn't be in pcmanfm or libfm-qt because the breeze icons are shown correctly in pcmanfm *under KDE*. Hence my guess about libqtxdg.

**Comment by tsujan** [comment]
@luis-pereira I guess you're familiar with those parts of LXQt. Would you please check them?

**Comment by luis-pereira** [comment]
@tsujan But if it's not used, how can the source of the problem be it ?
By the  sintomns lxqt-qtplugin can be an viable "suspect".

**Comment by tsujan** [comment]
@luis-pereira Yes, lxqt-qtplugin is a suspect too -- maybe the suspect No. 1.

**Comment by tsujan** [comment]
The question is: why doesn't LXQt see the structure in `/usr/share/icons/breeze/index.theme` correctly while it sees the other index files right? What's the crucial difference?

**Comment by palinek** [comment]
> @luis-pereira Yes, lxqt-qtplugin is a suspect too -- maybe the suspect No. 1.

I was suspecting the lxqt-qtplugin too.. but I see no difference also w/o using it (unsetting QT_QPA_PLATFORMTHEME)

**Comment by tsujan** [comment]
Forgive me if I'm totally lost because I'm not familiar with this part of LXQt at all:

I can only see `QIconTheme::QIconTheme(const QString &themeName)` in libqtxdg, which reads the index file.

**Comment by luis-pereira** [comment]
@palinek I just did the same test: unsetting `QT_QPA_PLATFORMTHEME`.  with the same results as you: no difference. In Sherlock Holmes style: _when you have eliminated the impossible, whatever remains, however improbable, must be the truth_. And the improbable one here is `QIconLoader/QIconLoaderEngine`. KDE uses it's own engine, PCManFm-Qt uses the one `QIcon` provides.

We are reaching the time to have our own LXQtIconLoaderEngine`.

@tsujan That code isn't run. libqtxdg isn't a plugin and pcmanfm-qt doesn't link to it. That code only runs when:

1. libqtxdg is linked
2. One uses `XdgIcon` instead of `QIcon`.

**Comment by YamashitaRen** [comment]
Before you go to far in the improbable, I'd like to remember everyone that the bug happens in Dolphin too on LXQt. It's even worse, directories are affected in Dolphin.

Now if my message is unnecessary, I hope you'll forgive me. The discussion has gone too far in the LXQt arcana for me to follow it...

**Comment by luis-pereira** [comment]
@YamashitaRen Dolphin on my LXQt
It would not surprise me if it were an bug in `QIcon`  `QIconLoader` engine. It as a good track record of bugs and not conformance to the standard.
![screen-2016-05-06-16-49-03](https://cloud.githubusercontent.com/assets/62877/15078382/d81cf114-13aa-11e6-9bb8-704423b7249f.png)

**Comment by palinek** [comment]
This is is pcmanfm-qt with breeze in freshly installed xfce session under manjaro
![screenshot](https://cloud.githubusercontent.com/assets/10990929/15078731/da5ede4c-13b4-11e6-9dae-809384203917.png)

This definitely leads us to the conclusion that QIconLoader in Qt is broken or the breeze icon theme is so specific, that it runs correctly in Qt only with the KDE icon loader

**Comment by tsujan** [comment]
> or the breeze icon theme is so specific, that it runs correctly in Qt only with the KDE icon loader

That should be the case, IMO. But specific in which way?

**Comment by tsujan** [comment]
Wow! I changed the names of folders `mimetypes/16` and `mimetypes/22` to `mimetypes/haha` and `mimetypes/lala` respectively and edited `index.theme` accordingly: the problem was fixed!!

So, it may be about a bug in QIconLoader, as you said.

**Comment by tsujan** [comment]
If the 16 and 24-px theme folder names start with an integer, the problem comes back; otherwise, no issue. That reminds me of `QString::toInt()`.

**Comment by luis-pereira** [comment]
Some findings, while killing time:
Thunar and SpaceFM also have the same problem:
## Thunar
![screen-2016-05-06-22-14-47]
(https://cloud.githubusercontent.com/assets/62877/15086589/c692b3b4-13d9-11e6-83f2-290c54a00d21.png)
![screen-2016-05-06-22-14-30](https://cloud.githubusercontent.com/assets/62877/15086590/c69717ce-13d9-11e6-9bb2-e11484b35edb.png)

### SpaceFM
![screen-2016-05-06-22-19-49](https://cloud.githubusercontent.com/assets/62877/15086601/d47e63ec-13d9-11e6-88a9-1e10dd3ce28c.png)
![screen-2016-05-06-22-19-06](https://cloud.githubusercontent.com/assets/62877/15086602/d48765a0-13d9-11e6-8d32-a76fddc824cc.png)

**Comment by tsujan** [comment]
@luis-pereira Strange! Both are OK here. This is Thunar:

![2016-05-07-02 12 19-scrot](https://cloud.githubusercontent.com/assets/981076/15086904/75b02bf0-13f9-11e6-9b41-470c70b625ac.png)

In the mean time, I couldn't find any flaw in qt-base → `src/gui/imge/qiconloader.cpp`. So, I don't understand yet why the problem is fixed when I set `Type=Fixed` under `[mimetypes/22]` in Breeze's intex file.

**Comment by tsujan** [comment]
Just one guess: In qt-base → `src/gui/imge/qiconloader.cpp` → `directoryMatchesSize()`, shouldn't this
````
    } else if (dir.type == QIconDirInfo::Scalable) {
        return dir.size <= dir.maxSize &&
                iconsize >= dir.minSize;
````
be
````
    } else if (dir.type == QIconDirInfo::Scalable) {
        return dir.size <= dir.maxSize &&
                iconsize >= dir.minSize && iconsize <= dir.maxSize;
````
instead?

**Comment by tsujan** [comment]
Yes!! That was the case. And it can be fixed in `lxqt-qtplugin`. This is pcmanfm-qt and (default) Breeze with modified `lxqt-qtplugin`:

![2016-05-07-05 37 51-scrot](https://cloud.githubusercontent.com/assets/981076/15089387/534d9228-1417-11e6-9772-880454bb084d.png)

Now I know lxqt-qtplugin a little better :)

@luis-pereira @palinek Could you make a PR? I could only the day after tomorrow.

**Comment by luis-pereira** [comment]
Until monday I don't have my dev machine.

**Comment by tsujan** [comment]
I wasn't as busy as I thought today :) The bug should be fixed by https://github.com/lxde/lxqt-qtplugin/pull/9. I tested it both on Debian and on Manjaro.

BTW, Breeze-5.4.x has a bug in 48-pix places icons. It's fixed in v5.21.0. So if you test it on Debian and with 48-px icons, the size of 48-px folder icons will be incorrect. You could manually fix that by setting `Type=Scalable` under `/usr/share/icons/breeze/index.theme` → `[places/32]`.

**Comment by palinek** [comment]
Now everything needed has been landed in master of lxde/lxqt-qtplugin & lxde/libqtxdg and the issue should be solved.

If not, feel free to reopen

**Comment by joshuakraemer** [comment]
The wrong icons are still shown on my machine with pcmanfm-qt-0.16.0 and lxqt-qtplugin-0.16.0.

This is pcmanfm-qt in lxqt (note mixed icons in side panel):
![lxqt](https://user-images.githubusercontent.com/10373011/114867440-1df3d700-9df5-11eb-83be-df082ce8283c.png)

And this is pcmanfm-qt in fvwm (even worse, wrong icons in main view):
![fvwm](https://user-images.githubusercontent.com/10373011/114867589-4aa7ee80-9df5-11eb-9de3-dfc69ddcdd6a.png)

**Comment by tsujan** [comment]
@joshuakraemer
Not reproducible.

As in fvwm, the icons aren't controlled by LXQt — unless you use `lxqt` for `QT_QPA_PLATFORMTHEME`.

BTW, LXQt 0.17.0 was released today.
