### ISSUE TITLE
Theme broke after update

### ISSUE THREAD

**Issue by rcmn** [lxde/lxqt#461]
Last night after an update the default theme broke and a reset to default does not fix it.
Does anyone experience this ?
it seems like no matter what i try to change nothing apply , background color , etc...even after a logout. 

![themebug](https://cloud.githubusercontent.com/assets/7894735/5952149/818c0f04-a797-11e4-9659-9648241b7d2e.png)
Ubuntu repo.

**Comment by hterh** [comment]
When  I tried to change the LXQt theme I noticed changes in color of time widget and start button whereby these icons are no longer visible. And changing themes is no longer possible. (Xubuntu/LxQt)

**Comment by luis-pereira** [comment]
It looks like has if the .qss aren't found.

**Comment by intialonso** [comment]
Confirmed here.

Running lxqt-panel in a terminal gives:

Teme: Cannot open file for reading: "/lxqt-panel.qss" But the files are there.

**Comment by intialonso** [comment]
@paulolieuthier the problem seems to be the caps in the name.

The folder themes are named in lower caps, but in the lxqt-config-appearance are capitalized, so the file ./config/lxqt.com set the "theme" line with the cap, so the system cant find the theme.

A quick fix could be to revert the caps change or to update the themes folders to the same names.

**Comment by intialonso** [comment]
Fixed. Please update lxqt-common and test.

fbc22d48f08eb206944b8aa29ea0b7daf350182b

**Comment by paulolieuthier** [comment]
@intialonso what happened with the folders directories renaming? The problem is back.

**Comment by intialonso** [comment]
It was this commit: https://github.com/lxde/lxqt-common/pull/18

**Comment by paulolieuthier** [comment]
0.9's tarball has all themes' names lowercase. And it's expected to be capitalized. This is causing problems. Update lxqt-common and delete `theme` entry in `~/.config/lxqt.conf`.

**Comment by intialonso** [comment]
Yes, the proble was that I merged this:
https://github.com/lxde/lxqt/issues/471

But I dont know how to undo that change in github, can you help me?

2015-02-09 17:35 GMT-05:00 Paulo Lieuthier <notifications@github.com>:

**Comment by intialonso** [comment]
I undo the change making a new commit.

2015-02-09 17:46 GMT-05:00 Inti <intialonso@gmail.com>:

**Comment by paulolieuthier** [comment]
@intialonso nice, problem fixed. @jleclanche this a problem for 0.9, right?

**Comment by jleclanche** [comment]
I have a 0.9.1 re-release planned for lxqt-common within 2-3 days. If you
have stuff to land on it, land it.

J. Leclanche

2015-02-09 23:55 GMT+01:00 Paulo Lieuthier <notifications@github.com>:

**Comment by stefonarch** [comment]
Hi all,

is there somebody who ever tried install LXQt on PPC?
Maybe ubuntu per PPC +ppa?

thanks
stefano
