### ISSUE TITLE
Several applications not starting

### ISSUE THREAD

**Issue by antis81** [lxde/lxqt#808]
About a week ago, I opened issue #797, just to state, that I'm experiencing problems with running LXQt on Lubuntu 15.04. Unfortunately the issue got closed immediately. What happened? Have I been too raw? If so, I apologize. My goal is in helping to solve/clarify those issues, making LXQt a stable and great user experience. Unfortunately this is also a question of time - so I don't see a chance in coding stuff right now and stick with reporting issues, as I see them.

So ... I'm not exactly sure, but it looks, some applications simply are not up-to-date with `liblxqt` API. Here's a list of what's working and what is not:

Starts | Application/Component | Error
---- | ---- | ----
:x: | lxqt-config | lxqt-config: symbol lookup error: lxqt-config: undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE
:x: | lxqt-config-monitor | lxqt-config-monitor: symbol lookup error: lxqt-config-monitor: undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE
:x: | lxqt-config-appearance | lxqt-config-appearance: symbol lookup error: lxqt-config-appearance: undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE
:x: | lxqt-config-input | lxqt-config-input: symbol lookup error: lxqt-config-input: undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE
:x: | lxqt-config-file-associations | lxqt-config-file-associations: symbol lookup error: lxqt-config-file-associations: undefined symbol: _ZN4LxQt17SingleApplicationC1ERiPPcNS0_12StartOptionsE
:white_check_mark: | lxqt-policykit-agent | --
:white_check_mark: | lxqt-globalkeysd | --
:white_check_mark: | lxqt-powermanagement | --
:white_check_mark: | lxqt-openssh-askpass | --
:white_check_mark: | lxqt-about | --
:white_check_mark: | lxqt-admin-user | --
:white_check_mark: | lxqt-admin-time | --
:white_check_mark: | lxqt-config-globalkeyshortcuts | --
:white_check_mark: | lxqt-config-session | --
:white_check_mark: | lxqt-config-notificationd | --
:white_check_mark: | lxqt-config-powermanagement | --
:white_check_mark: | lxqt-leave | --
:white_check_mark: | lxqt-session | -- 
:white_check_mark: | lxqt-runner | -- 

Anything I forgot?

System info:

Component | Version
---- | ----
Hardware | Macbook 2,1 (late 2007, plastic)
Distro | Lubuntu 15.04
LXQt | >0.9 from lubuntu-daily ppa

I'm aware of the fact, you are preparing for Lubuntu 15.10 and I'm happy, when I can finally get rid of the `lubuntu-daily` PPA. At present I don't see the chance yet.

**Comment by pmattern** [comment]
> Unfortunately the issue got closed immediately. What happened? Have I been too raw?

You weren't, no worries, man.

But just consider the workflow: the LXDE project is developing the LXQt desktop environment. This tracker as well as all component-specific ones on GitHub such as https://github.com/lxde/pcmanfm-qt/issues are meant to track problems regarding this development.
Next distributions pick up the code and pack it into their genuine binary packages. Problems arising in that process are beyond the scope of our responsibility and have to be dealt with on their tracker. The latter even applies in the somewhat special situation that @gilir is both one of the PPA maintainers and member of the LXDE team.

That said I can reproduce you findings in a Lubuntu 15.04 VM here while they don't exist running latest VCS code on Arch Linux. So...

**Comment by paulolieuthier** [comment]
Let's open this so that *buntu users can understand what is going on until @gilir fixes the problem, as discussed in #799.

**Comment by gilir** [comment]
I just start a rebuild of lxqt-config, to pick the last liblxqt. That should fix the problem. Please, when you break API so badly without a SONAME bump, please contact me directly so I can prepare the rebuild for all the components.

**Comment by antis81** [comment]
@gilir Works! Thanks in the name of all *buntu users!

@celiapgt FYI

**Comment by pmattern** [comment]
In the name of a not so large number of *buntu users: problem still exists in lxqt-panel on Ubuntu 14.04 as described in #800 which may or may not be related to the inconsistency depicted [here](https://github.com/lxde/lxqt/issues/800#issuecomment-137210208) which persists as well.

**Comment by antis81** [comment]
@paulolieuthier Sorry, couldn't check for `lxqt-panel` (I'm happy with cairo-dock) can you reopen please?

Further, `lxqt-leave` segfaults with latest upgrade. Looks like this is also related ot liblxqt.

@gilir Can you update the two packages (`lxqt-leave` and `lxqt-panel`) please -> everything else is working again. Sorry for the hassle…

**Comment by gilir** [comment]
lxqt-panel on 14.04 doesn't build anymore because the requirement for kf5 is too high. I need more time to fix it that the others (which only need to rebuild against the new liblxqt)

**Comment by celiapgt** [comment]
@antis81: I'm waiting for the whole fix. I had to switch to GNOME because I really need my machine. Thanks for the info. I hope LXQt is back againg ,all running. 

Guys, LXQt is superb (for me). Thanks. I'll keep waiting.

If I can help, I'll be glad to be useful.

**Comment by antis81** [comment]
@celiapgt I'm also LXQt user and really like it. Yes, everything should be ok with the packaging for ~2 months now.
