### ISSUE TITLE
plugin-mainmenu: malfunction due to key DBusActivatable in desktop entry files

### ISSUE THREAD

**Issue by pmattern** [lxde/lxqt#967]
Desktop entry files featuring `DBusActivatable=true` are handled faulty by plugin-mainmenu.

Running Debian stretch (testing) and LXQt 0.10 from the official repositories they just aren't launched, on Arch Linux running LXQt from recent VCS checkouts, among other lxde/lxqt-panel@b0f6d23, they trigger a crash / core dump of the panel altogether.

The key belongs to the [officially supported ones](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html). On both systems the desktop entry file was launched flawlessly from the main menu of LXPanel, so the problem seems to be at LXQt's side.
A sample desktop entry file making use of the key is the one of `dconf-editor`.

Notes on the crashes on Arch Linux:
The fact that the panel crashes on Arch Linux may eventually be due to some suspected glibc issue on that distribution I'm trying to track down for about a week to no avail. More information can e. g. be found in https://bbs.archlinux.org/viewtopic.php?id=209466, https://bugs.archlinux.org/task/48336 and https://bbs.archlinux.org/viewtopic.php?id=209340. Any help to get ahead with this would be much appreciated.
Crash logs are at https://gist.github.com/pmattern/7665e4b5078c9e762362.

**Comment by palinek** [comment]
This is due to a discrepancy in the name of .desktop file (at least on my machine):
The desktop file is `/usr/share/applications/ca.desrt.dconf-editor.desktop`. The spec (I can't cite because freedesktop.org is currently down) says that the DBus service and path for invocation are assembled based on the filename. That is service = *ca.desrt.dconf-editor*, path = */ca/desrt/dconf-editor*.

Based on the dbus introspcetion (qdbusviewer) this is aparently wrong on my system: service = *ca.desrt.dconf*, path = */ca/desrt/dconf*

This of course doesn't mean it should crash the app. I'll have a look into libqtxdg.

**Comment by palinek** [comment]
@pmattern Can you, please, check if lxde/libqtxdg@88d4bafa fixes the crash?

**Comment by palinek** [comment]
...actually the crash probably happens because of the invalid path (freedesktop.org is up now :smile:) -> https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path

The lxde/libqtxdg@9a8545b should do the checking job correctly.

**Comment by palinek** [comment]
@pmattern please, make your tests with lxqt/libqtxdg#75

Note: *nautilus* has also DBusActivatable .desktop file

**Comment by palinek** [comment]
Fixed by lxde/libqtxdg#75

**Comment by pmattern** [comment]
Running yesterday's VCS checkouts including lxde/libqtxdg@0a66207 on Arch Linux the core dumps of the panel have gone but e. g. `dconf-editor` still doesn't get launched by its desktop entry file. (It's working flawlessly if invoked from a virtual terminal.)

**Comment by palinek** [comment]
What is the name of dconf editor desktop file?

**Comment by pmattern** [comment]
`ca.desrt.dconf-editor.desktop`. Same file (checksum) in Arch Linux and current Debian testing. After removing `DBusActivatable=true` the application does start.

**Comment by palinek** [comment]
> ca.desrt.dconf-editor.desktop. Same file (checksum) in Arch Linux and current Debian testing. After removing DBusActivatable=true the application does start.

Then I don't understand reopening this issue. I've clearly described that in [this](#issuecomment-191155855) and [this](#issuecomment-191175620) that this is an issue of *dconf editor* and its **invalid** .desktop file.

**Comment by pmattern** [comment]
Using the said desktop entry file `dconf-editor` gets apparently launched flawlessly in LXDE, KDE Plasma 5 and Xfce. My knowledge regarding D-Bus doesn't allow for judging what exactly is happening in these desktop environments.

Dconf doesn't seem to be developed actively any longer, at first glance I couldn't even find a suitable upstream bugtracker. Yet it's still used by many GTK applications AFAIK.
So all in all I figure this particular desktop entry file of `dconf-editor` could bite us somehow.

So besides that particular file is to blame her I wonder whether implementing a workaround isn't worth the pain.
Maybe run the command stated by key `Exec` instead of doing nothing at all upon getting aware something's rotten with a desktop entry file featuring `DBusActivatable`? According to the [spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html) as cited above files using `DBusActivatable` should still provide key `Exec` as  fallback.

**Comment by palinek** [comment]
> Using the said desktop entry file dconf-editor gets apparently launched flawlessly in LXDE, KDE Plasma 5 and Xfce.

Do they start it by DBus?

> According to the spec as cited above files using DBusActivatable should still provide key Exec as fallback.

Yes, and the very same spec says: ` If the value is true then implementations should ignore the Exec key and send a D-Bus message to launch the application.`

I don't know if there were any changes in the DBus specification ([allowed characters in the object paths](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path)), but the dbus activation was definitely working with the old implementation (actually I was testing with dconf while implementing the feature)... But something has changed in the Qt implementation and now it doesn't allow invalid paths -> that's the assert that you are observing.

**Comment by luis-pereira** [comment]
@pmattern @palinek Can lxde/libqtxdg#80 nail it ?

**Comment by luis-pereira** [comment]
The culprit where is the `-` in `ca.desrt.dconf-editor`. It's not part of the allowed characters.

**Comment by pmattern** [comment]
@luis-pereira 
Using lxde/libqtxdg@29652fb dconf-editor gets launched using its faulty desktop entry file, too.
I think it's pretty good to have this fallback feature for the reasons stated [above](https://github.com/lxde/lxqt/issues/967#issuecomment-192989815).

On a side-note I'm not that sure whether lxde/libqtxdg@b9af1d3 really violates the specification. Sure, it says
>  If the value is true then implementations should ignore the Exec key and send a D-Bus message to launch the application.

But actually that's what LXQt still does *as first step*. Actually, the said commits rather sort of complement the specification with an *additional* fallback in case launching via D-Bus fails (which is a use-case that pretty much should actually be covered by the specification in the first place, IMO).

**Comment by luis-pereira** [comment]
@palinek The specification states that if the DBusActivatable key is present, the Exec should be ignored.
You are not doing that.

**Comment by palinek** [comment]
> @palinek The specification 

Me? It was meant to @pmattern, right?

**Comment by luis-pereira** [comment]
@palinek Yes, Sorry ...
